### ISSUE TITLE
404

### ISSUE THREAD

**Issue by ManishKhullar** [MAKLEO/source#1]
Needed inputs how to create a portfolio on GitHub pages

**Comment by hemantsonu20** [comment]
Github provides two type of github pages of for your account which will be accessible at `{username}.github.io`. Another for repo, which will be accessible at `{username}.github.io/{repo-name}`.
For portfolio, you need to create a repo named `MAKLEO.github.io`. Upload your html codes to the repo, configure github pages from the setting repository. That's it. This is my portfolio: http://hemantsonu20.github.io/

**Comment by ManishKhullar** [comment]
Thanks for the insight
